version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /app/oauth2-proxy.cfg --cookie-secure=true
    ports:
      - 80:4180
    volumes:
      - app_data:/app
    hostname: oauth2-proxy
    restart: unless-stopped
  streamlit:
    image: authstreamlit.azurecr.io/test-streamlit:latest
    expose:
     - "8501"
    volumes:
      - app_data:/app/
    restart: unless-stopped

volumes:
  app_data:
