version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180/tcp
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
      - "./emails.txt:/app/emails.txt"
    restart: unless-stopped
  shiny:
    image: test-shiny:latest
    expose:
     - "3838"
    restart: unless-stopped
